[aws]
disabled = true

[crystal]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[julia]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[php]
disabled = true

[terraform]
disabled = true

[zig]
disabled = true

[purescript]
disabled = true
